CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    normalized_username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE auth_client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_client_id CHAR(36) NOT NULL UNIQUE,
    client_id VARCHAR(100) NOT NULL UNIQUE,
    client_secret_hash VARCHAR(255) NOT NULL,
    client_name VARCHAR(200) NOT NULL,
    status VARCHAR(16) NOT NULL,
    audience VARCHAR(100) NOT NULL,
    scopes VARCHAR(1000) NOT NULL,
    access_token_ttl_seconds INT NOT NULL,
    secret_expires_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);
