package ning.linkverse.identity.infrastructure.persistence;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.DelegatingPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.oauth2.core.AuthorizationGrantType;
import org.springframework.security.oauth2.core.ClientAuthenticationMethod;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClient;
import org.springframework.security.oauth2.server.authorization.settings.ClientSettings;
import org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat;
import org.springframework.security.oauth2.server.authorization.settings.TokenSettings;

import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * IdentityJdbcRegisteredClientRepositoryComponentTest 通过内存数据库验证自定义客户端仓储映射。
 *
 * @author ning
 * @date 2026-08-19
 */
class IdentityJdbcRegisteredClientRepositoryComponentTest {

    private JdbcTemplate jdbcTemplate;
    private IdentityJdbcRegisteredClientRepository repository;
    private PasswordEncoder passwordEncoder;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:identity-client-" + UUID.randomUUID()
                + ";MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE auth_client (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    registered_client_id CHAR(36) NOT NULL UNIQUE,
                    client_id VARCHAR(100) NOT NULL UNIQUE,
                    client_secret_hash VARCHAR(255) NOT NULL,
                    client_name VARCHAR(200) NOT NULL,
                    status VARCHAR(16) NOT NULL,
                    audience VARCHAR(100) NOT NULL,
                    scopes VARCHAR(1000) NOT NULL,
                    access_token_ttl_seconds INT NOT NULL,
                    secret_expires_at TIMESTAMP(6),
                    created_at TIMESTAMP(6) NOT NULL,
                    updated_at TIMESTAMP(6) NOT NULL
                )
                """);
        repository = new IdentityJdbcRegisteredClientRepository(jdbcTemplate, new ObjectMapper());
        passwordEncoder = new DelegatingPasswordEncoder(
                "bcrypt",
                Map.of("bcrypt", new BCryptPasswordEncoder(4))
        );
    }

    @Test
    void shouldRoundTripMinimalClientCredentialsClient() {
        RegisteredClient client = serviceClient(
                UUID.randomUUID().toString(),
                "linkverse-trade",
                "trade-service-secret-000000000000"
        );

        repository.save(client);

        RegisteredClient restored = repository.findByClientId("linkverse-trade");
        assertThat(restored).isNotNull();
        assertThat(restored.getId()).isEqualTo(client.getId());
        assertThat(restored.getClientSecret()).isEqualTo(client.getClientSecret());
        assertThat(restored.getClientAuthenticationMethods())
                .containsExactly(ClientAuthenticationMethod.CLIENT_SECRET_BASIC);
        assertThat(restored.getAuthorizationGrantTypes())
                .containsExactly(AuthorizationGrantType.CLIENT_CREDENTIALS);
        assertThat(restored.getScopes()).containsExactly("payment.internal");
        String audience = restored.getClientSettings().getSetting(
                IdentityJdbcRegisteredClientRepository.AUDIENCE_SETTING
        );
        assertThat(audience).isEqualTo("linkverse-payment");
        assertThat(restored.getTokenSettings().getAccessTokenFormat())
                .isEqualTo(OAuth2TokenFormat.SELF_CONTAINED);
        assertThat(restored.getTokenSettings().getAccessTokenTimeToLive())
                .isEqualTo(Duration.ofMinutes(5));
        assertThat(jdbcTemplate.queryForObject(
                "SELECT scopes FROM auth_client WHERE client_id = ?",
                String.class,
                "linkverse-trade"
        )).isEqualTo("[\"payment.internal\"]");
    }

    @Test
    void shouldNotLoadDisabledClient() {
        RegisteredClient client = serviceClient(
                UUID.randomUUID().toString(),
                "linkverse-trade",
                "trade-service-secret-000000000000"
        );
        repository.save(client);
        jdbcTemplate.update("UPDATE auth_client SET status = 'DISABLED' WHERE client_id = ?", "linkverse-trade");

        assertThat(repository.findByClientId("linkverse-trade")).isNull();
        assertThat(repository.findById(client.getId())).isNull();
    }

    @Test
    void shouldRejectDuplicateClientIdWithSafeMessage() {
        repository.save(serviceClient(
                UUID.randomUUID().toString(),
                "linkverse-trade",
                "trade-service-secret-000000000000"
        ));

        assertThatThrownBy(() -> repository.save(serviceClient(
                UUID.randomUUID().toString(),
                "linkverse-trade",
                "another-trade-secret-00000000000"
        )))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("服务客户端标识已存在");
    }

    @Test
    void shouldRejectServiceTokenTtlOutsideDatabaseConstraint() {
        RegisteredClient client = RegisteredClient.from(serviceClient(
                        UUID.randomUUID().toString(),
                        "linkverse-trade",
                        "trade-service-secret-000000000000"
                ))
                .tokenSettings(TokenSettings.builder()
                        .accessTokenTimeToLive(Duration.ofSeconds(30))
                        .build())
                .build();

        assertThatThrownBy(() -> repository.save(client))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("服务访问令牌有效期须为 60 至 3600 秒");
    }

    private RegisteredClient serviceClient(String registeredClientId, String clientId, String rawSecret) {
        return RegisteredClient.withId(registeredClientId)
                .clientId(clientId)
                .clientIdIssuedAt(Instant.parse("2026-08-19T10:15:30Z"))
                .clientSecret(passwordEncoder.encode(rawSecret))
                .clientName("LinkVerse Trade")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
                .scope("payment.internal")
                .clientSettings(ClientSettings.builder()
                        .setting(
                                IdentityJdbcRegisteredClientRepository.AUDIENCE_SETTING,
                                "linkverse-payment"
                        )
                        .build())
                .tokenSettings(TokenSettings.builder()
                        .accessTokenFormat(OAuth2TokenFormat.SELF_CONTAINED)
                        .accessTokenTimeToLive(Duration.ofMinutes(5))
                        .build())
                .build();
    }
}
