#!/usr/bin/env bash
set -Eeuo pipefail

required_variables=(
  MYSQL_ROOT_PASSWORD
  IDENTITY_DB_NAME IDENTITY_APP_USER IDENTITY_APP_PASSWORD IDENTITY_MIGRATOR_USER IDENTITY_MIGRATOR_PASSWORD
  TRADE_DB_NAME TRADE_APP_USER TRADE_APP_PASSWORD TRADE_MIGRATOR_USER TRADE_MIGRATOR_PASSWORD
  PAYMENT_DB_NAME PAYMENT_APP_USER PAYMENT_APP_PASSWORD PAYMENT_MIGRATOR_USER PAYMENT_MIGRATOR_PASSWORD
)

for variable_name in "${required_variables[@]}"; do
  if [[ -z "${!variable_name:-}" ]]; then
    echo "缺少数据库初始化变量：${variable_name}" >&2
    exit 1
  fi
done

for identifier in \
  "${IDENTITY_DB_NAME}" "${IDENTITY_APP_USER}" "${IDENTITY_MIGRATOR_USER}" \
  "${TRADE_DB_NAME}" "${TRADE_APP_USER}" "${TRADE_MIGRATOR_USER}" \
  "${PAYMENT_DB_NAME}" "${PAYMENT_APP_USER}" "${PAYMENT_MIGRATOR_USER}"; do
  if [[ ! "${identifier}" =~ ^[a-z0-9_]+$ ]]; then
    echo "数据库名称或账号只能包含小写字母、数字和下划线：${identifier}" >&2
    exit 1
  fi
done

for password in \
  "${IDENTITY_APP_PASSWORD}" "${IDENTITY_MIGRATOR_PASSWORD}" \
  "${TRADE_APP_PASSWORD}" "${TRADE_MIGRATOR_PASSWORD}" \
  "${PAYMENT_APP_PASSWORD}" "${PAYMENT_MIGRATOR_PASSWORD}"; do
  if [[ ! "${password}" =~ ^[A-Za-z0-9_@%+=:,.-]{16,128}$ ]]; then
    echo "业务数据库密码必须为 16～128 位安全字符，且不得包含引号、空格或反斜杠。" >&2
    exit 1
  fi
done

# 每次重放都先清除旧授权，再按应用运行与迁移职责重新授予，避免权限逐步漂移。
MYSQL_PWD="${MYSQL_ROOT_PASSWORD}" mysql --protocol=socket --user=root <<SQL
CREATE DATABASE IF NOT EXISTS ${IDENTITY_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS ${TRADE_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS ${PAYMENT_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${IDENTITY_APP_USER}'@'%' IDENTIFIED BY '${IDENTITY_APP_PASSWORD}';
ALTER USER '${IDENTITY_APP_USER}'@'%' IDENTIFIED BY '${IDENTITY_APP_PASSWORD}';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${IDENTITY_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ${IDENTITY_DB_NAME}.* TO '${IDENTITY_APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${IDENTITY_MIGRATOR_USER}'@'%' IDENTIFIED BY '${IDENTITY_MIGRATOR_PASSWORD}';
ALTER USER '${IDENTITY_MIGRATOR_USER}'@'%' IDENTIFIED BY '${IDENTITY_MIGRATOR_PASSWORD}';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${IDENTITY_MIGRATOR_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES
  ON ${IDENTITY_DB_NAME}.* TO '${IDENTITY_MIGRATOR_USER}'@'%';

CREATE USER IF NOT EXISTS '${TRADE_APP_USER}'@'%' IDENTIFIED BY '${TRADE_APP_PASSWORD}';
ALTER USER '${TRADE_APP_USER}'@'%' IDENTIFIED BY '${TRADE_APP_PASSWORD}';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${TRADE_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ${TRADE_DB_NAME}.* TO '${TRADE_APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${TRADE_MIGRATOR_USER}'@'%' IDENTIFIED BY '${TRADE_MIGRATOR_PASSWORD}';
ALTER USER '${TRADE_MIGRATOR_USER}'@'%' IDENTIFIED BY '${TRADE_MIGRATOR_PASSWORD}';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${TRADE_MIGRATOR_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES
  ON ${TRADE_DB_NAME}.* TO '${TRADE_MIGRATOR_USER}'@'%';

CREATE USER IF NOT EXISTS '${PAYMENT_APP_USER}'@'%' IDENTIFIED BY '${PAYMENT_APP_PASSWORD}';
ALTER USER '${PAYMENT_APP_USER}'@'%' IDENTIFIED BY '${PAYMENT_APP_PASSWORD}';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${PAYMENT_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ${PAYMENT_DB_NAME}.* TO '${PAYMENT_APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${PAYMENT_MIGRATOR_USER}'@'%' IDENTIFIED BY '${PAYMENT_MIGRATOR_PASSWORD}';
ALTER USER '${PAYMENT_MIGRATOR_USER}'@'%' IDENTIFIED BY '${PAYMENT_MIGRATOR_PASSWORD}';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${PAYMENT_MIGRATOR_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES
  ON ${PAYMENT_DB_NAME}.* TO '${PAYMENT_MIGRATOR_USER}'@'%';
SQL
